_target_: pytorch_lightning.Trainer
default_root_dir: "${paths.output_dir}"
gradient_clip_val: 0.5
devices: "auto"
max_epochs: 30
log_every_n_steps: 100
accelerator: "auto"
strategy: "ddp_find_unused_parameters_false"
sync_batchnorm: true
benchmark: true
deterministic: false
replace_sampler_ddp: false
