_target_: src.models.losses.CasPLoss
coarse_cls_sparse: true
coarse_cls_loss_pos_weight: 1.0
coarse_cls_loss_neg_weight: 1.0
extra_coarse_cls_sparse: true
extra_coarse_cls_loss_pos_weight: 0.5
extra_coarse_cls_loss_neg_weight: 0.5
