_target_: src.models.MatchingModule

net:
    _target_: src.models.nets.CasP
    encoder: "repvgg_a1"
    rope:
        _target_: src.models.nets.RoPESinePositionalEncoding
        depth: 256
        train_size: ???
        test_size: ???
        fp16: ${fp16}
    coarse_matching:
        _target_: src.models.nets.CoarseMatching
        decoder:
            _target_: src.models.nets.decoders.Decoder
            stride: 2
            topk: 8
            dims:
                - 256
                - 64
            num_x_layers: 4
            num_y_layers: 2
            num_heads: 8
    extra_scale: 16

loss:
    _target_: src.models.losses.NewMatcherLoss
    coarse_cls_sparse: true
    coarse_cls_loss_pos_weight: 1.0
    coarse_cls_loss_neg_weight: 1.0
    extra_coarse_cls_sparse: false
    extra_coarse_cls_loss_pos_weight: 0.5
    extra_coarse_cls_loss_neg_weight: 0.5

optimizer: ???

scheduler: ???

train_batch_size_per_gpu: ${data.train_batch_size_per_gpu}

test_fp16_precision: ${fp16}

canonical_batch_size: ???

canonical_learning_rate: ???

canonical_warmup_step_count: ???

warmup_ratio: ???

end_point_thresholds: ???

epipolar_thresholds: ???

pose_ransac_count: ???

pose_thresholds: ???
