defaults:
  - default
  - _self_

net:
  type: "one_stage"
  fine_preprocess:
    _target_: src.models.components.nets.new_matcher.FinePreprocess
    type: "eloftr"
    window_size: 5
    stride: 4
    padding: 2
    depths:
        - ${model.net.backbone.layer_depths.0}
        - ${model.net.backbone.layer_depths.0}
        - ${model.net.backbone.layer_depths.1}
#  fine_module:
#    _target_: src.models.components.nets.new_matcher.LoFTR
#    encoder:
#      _target_: src.models.components.nets.new_matcher.TransformerEncoder
#      depth: ${model.net.backbone.layer_depths.0}
#      heads_count: 8
#      attention:
#        _target_: src.models.components.nets.new_matcher.FullAttention
#    types: ["self", "cross"]
  fine_cls_matching:
    _target_: src.models.components.nets.new_matcher.FineMatching
    type: "classification"
    depth: ${model.net.backbone.layer_depths.0}
    window_size: 8
    temperature: 1.0
    cls_offset: 0.5
  fine_reg_matching:
    _target_: src.models.components.nets.new_matcher.homo.FineHomo

loss:
  _target_: src.models.components.losses.NewMatcherLoss
  coarse_cls_sparse: true
  coarse_cls_loss_pos_weight: 0.5
  coarse_cls_loss_neg_weight: 0.5
  extra_coarse_cls_sparse: true
  extra_coarse_cls_loss_pos_weight: 0.5
  extra_coarse_cls_loss_neg_weight: 0.5
  fine_cls_sparse: true
  fine_cls_loss_pos_weight: 0.25
  fine_cls_loss_neg_weight: 0.25
  fine_reg_loss_weight: 1.0
  dense_reg_loss_weight: 1.0
