_target_: src.models.MatchingModule

net:
  _target_: src.models.components.nets.new_matcher.NewMatcherNet
  type: "three_stage"
  backbone:
    _target_: src.models.components.nets.new_matcher.backbones.create_resnet_selfcoc_fpn
  positional_encoding:
    _target_: src.models.components.nets.new_matcher.modules.positional_encoding.SinePositionalEncoding
    depth: 256
    train_size: ???
  coarse_module:
    _target_: src.models.components.nets.new_matcher.GlobalCoC
    scale: 2
    in_depth: 256
    hidden_depth: 256
    heads_count: 8
    types: ["cross", "cross", "cross", "cross"]
    use_matchability: true
  coarse_matching_16x:
    _target_: src.models.components.nets.new_matcher.CoarseMatching
    type: "unidirectional"
    use_matchability: ${model.net.coarse_module.use_matchability}
  coarse_matching_8x:
    _target_: src.models.components.nets.new_matcher.CoarseMatching
    type: "bidirectional"
  fine_cls_matching_2x:
    _target_: src.models.components.nets.new_matcher.FineMatching
    type: "classification"
    depth: 64
    window_size: 8
    temperature: 1.0
  fine_module:
    _target_: src.models.components.nets.new_matcher.LoFTR
    depth: 64
    heads_count: 8
    attention:
      _target_: src.models.components.nets.new_matcher.FullAttention
    types: ["self", "cross"]
  fine_cls_matching_1x:
    _target_: src.models.components.nets.new_matcher.FineMatching
    type: "classification"
    depth: 64
    window_size: 5
    temperature: 1.0
  fine_reg_matching:
    _target_: src.models.components.nets.new_matcher.FineMatching
    type: "regression_by_expectation"
    depth: 64
    window_size: 3
    temperature: 10.0

loss:
  _target_: src.models.components.losses.NewMatcherLoss
  coarse_cls_sparse_16x: ???
  coarse_cls_loss_pos_weight_16x: 1.0
  coarse_cls_loss_neg_weight_16x: 1.0
  coarse_cls_sparse_8x: ???
  coarse_cls_loss_pos_weight_8x: 1.0
  coarse_cls_loss_neg_weight_8x: 1.0
  fine_cls_sparse_2x: ???
  fine_cls_loss_pos_weight_2x: 1.0
  fine_cls_loss_neg_weight_2x: 1.0
  fine_cls_sparse_1x: ???
  fine_cls_loss_pos_weight_1x: 1.0
  fine_cls_loss_neg_weight_1x: 1.0
  fine_reg_loss_weight: 1.0

optimizer: ???

scheduler: ???

train_batch_size_per_gpu: ${data.train_batch_size_per_gpu}

canonical_batch_size: ???

canonical_learning_rate: ???

canonical_warmup_step_count: ???

warmup_ratio: ???

end_point_thresholds: ???

epipolar_thresholds: ???

pose_thresholds: ???
