defaults:
  - default
  - _self_

net:
  type: "two_stage"
  fine_preprocess:
    _target_: src.models.components.nets.new_matcher.FinePreprocess
    type: "eloftr"
    window_size: 8
    stride: 8
    padding: 0
    right_extra: 1
    scale_before_crop: 2
    depths: ${model.net.backbone.layer_depths}
  fine_module:
    _target_: src.models.components.nets.new_matcher.LoFTR
    encoder:
      _target_: src.models.components.nets.new_matcher.AggregatedEncoder
      depth: ${model.net.fine_preprocess.depths.0}
      heads_count: 8
      scale: 2
      attention:
        _target_: src.models.components.nets.new_matcher.FullAttention
    types: ["self", "cross"]
  fine_cls_matching:
    _target_: src.models.components.nets.new_matcher.FineMatching
    type: "classification"
    depth: 56
    window_size: ${model.net.fine_preprocess.window_size}
    temperature: 1.0
    cls_offset: 0.5
  fine_reg_matching:
    _target_: src.models.components.nets.new_matcher.FineMatching
    type: "regression_by_expectation"
    depth: 8
    window_size: 3
    temperature: 10.0

loss:
  _target_: src.models.components.losses.NewMatcherLoss
  coarse_cls_sparse: true
  coarse_cls_loss_pos_weight: 0.5
  coarse_cls_loss_neg_weight: 0.5
  extra_coarse_cls_sparse: true
  extra_coarse_cls_loss_pos_weight: 0.5
  extra_coarse_cls_loss_neg_weight: 0.5
  fine_cls_sparse: true
  fine_cls_loss_pos_weight: 0.25
  fine_cls_loss_neg_weight: 0.25
  fine_reg_loss_weight: 0.25
