_target_: modules.src.models.components.nets.new_matcher.NewMatcherNet
type: ???
backbone:
  _target_: modules.src.models.components.repvgg.create_RepVGG_B0
rope:
  _target_: modules.src.models.components.nets.new_matcher.RoPESinePositionalEncoding
  depth: ${local_coc.layer_depths.0}
  train_size: [832, 832]
  fp16: false
local_coc:
  _target_: modules.src.models.components.nets.new_matcher.LocalCoC
  initial_depth: 256
  scales: [2, 2]
  blocks_counts: [2, 2]
  layer_depths: [256, 256]
  hidden_depths: [256, 256]
  heads_counts: [8, 8]
  center_sizes: [4, 2]
  fold_sizes: [1, 1]
coarse_module:
  _target_: modules.src.models.components.nets.new_matcher.GlobalCoC
  scale: 2
  in_depth: ${local_coc.layer_depths.0}
  hidden_depth: ${coarse_module.in_depth}
  heads_count: 8
  layer_count: 2
  attention_block:
    _target_: modules.src.models.components.nets.new_matcher.AggregatedEncoder
    depth: ${coarse_module.in_depth}
    heads_count: ${coarse_module.heads_count}
    scale: ${coarse_module.scale}
    attention:
      _target_: modules.src.models.components.nets.new_matcher.Attention
coarse_matching:
  _target_: modules.src.models.components.nets.new_matcher.CoarseMatching
  fused_selective_module:
    _target_: modules.src.models.components.nets.new_matcher.FusedSelectiveTransformer
    scale: 2
    depths:
      - 256
      - ${local_coc.layer_depths.0}
    encoder:
      _target_: modules.src.models.components.nets.new_matcher.ConvTransformerEncoder
      scale: ${coarse_matching.fused_selective_module.scale}
      depth: ${coarse_matching.fused_selective_module.depths.0}
      heads_count: 8
      attention:
        _target_: modules.src.models.components.nets.new_matcher.Attention
    layer_count: 2
  temperature: 0.1
  train_percent: 0.3
  train_min_gt_count: 100
fine_preprocess: ???
#  fine_module: ???
fine_reg_matching: ???
extra_scale: 16
enable_crop: false
