defaults:
  - default
  - _self_

type: "one_stage"
fine_preprocess:
  _target_: modules.src.models.components.nets.new_matcher.FinePreprocess
  type: "eloftr"
  window_size: 5
  stride: 4
  padding: 2
  depths: [64, 128, 256]
# fine_module:
#   _target_: src.models.components.nets.new_matcher.LoFTR
#   encoder:
#     _target_: src.models.components.nets.new_matcher.TransformerEncoder
#     depth: ${model.net.backbone.layer_depths.0}
#     heads_count: 8
#     attention:
#       _target_: src.models.components.nets.new_matcher.FullAttention
#   types: ["self", "cross"]
# fine_cls_matching:
#   _target_: src.models.components.nets.new_matcher.FineMatching
#   type: "classification"
#   depth: ${model.net.backbone.layer_depths.0}
#   window_size: 8
#   temperature: 1.0
#   cls_offset: 0.5
fine_reg_matching:
  _target_: modules.src.models.components.nets.new_matcher.FineMatching
  type: "regression_by_expectation"
  depth: 64
  window_size: 5
