model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: "${paths.output_dir}/checkpoints"
  filename: "epoch={epoch}-coarse_precision={val_metric/coarse_precision:.3f}"
  monitor: "val_metric/coarse_precision"
  verbose: true
  save_last: true
  save_top_k: 15
  mode: "max"
  auto_insert_metric_name: false
