model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: "${paths.output_dir}/checkpoints"
  filename: "epoch={epoch}-auc@5={val_metrics/pose_auc@5:.3f}-auc@10={val_metrics/pose_auc@10:.3f}-auc@20={val_metrics/pose_auc@20:.3f}"
  monitor: "val_metrics/pose_auc@10"
  verbose: true
  save_last: true
  save_top_k: 15
  mode: "max"
  auto_insert_metric_name: false
