# @package _global_

defaults:
  - _self_
  - data: ???
  - model: ???
  - logger: null
  - trainer: ???
  - paths: default
  - extras: default
  - hydra: default
  - experiment: ???

task_name: "eval"

tags: ???

train: false

test: true

ckpt_path: ???

seed: 66
