# @package _global_

defaults:
    - _self_
    - data: ???
    - model: ???
    - logger: null
    - trainer: ???
    - paths: default
    - extras: default
    - hydra: default
    - experiment: ???

task_name: "eval"
tags: ???
train: False
test: True
fp16: False
ckpt_path: ???
seed: 66
