_target_: src.models.nets.CasP_O
config:
    train_size: 832
    test_size: null
    threshold: 0.2
    border_removal: 2
    # ----------
    scales: [8, 4]
    data_mode: "gray"
    data_factor: 16
    dim_list: [64, 128, 256]
    # ----------
    encoder:
        name: "repvgg"
        dim_list: ${..dim_list}
        num_blocks_list: [2, 4, 14]
    decoder:
        dim_list:
            - ${...dim_list.2}
            - ${...dim_list.1}
        num_heads_list: [8, 4]
        num_layers_list: [4, 2]
        stride_list: [2]
        topk_list: [8]
        global_patch_size: 2
        factor: 16
        train_size: ${..train_size}
        test_size: ${..test_size}
    coarse_matching:
        stride_list: ${..decoder.stride_list}
        threshold: ${..threshold}
        border_removal: ${..border_removal}
